### ISSUE TITLE
Support `limit` stream option

### ISSUE THREAD

**Issue by marcbachmann** [flumedb/flumelog-memory#1]
What do you think about this solution?
Btw. the tests are failing in master, but I guess there's an issue in the test suite.
```patch
diff --git a/index.js b/index.js
index 0cdf253..0c7628d 100644
--- a/index.js
+++ b/index.js
@@ -66,6 +66,7 @@ module.exports = function (filename) {
       var reverse = opts.reverse
       var min  = opts.gt != null ? opts.gt + 1 : opts.gte != null ? opts.gte : 0
       var max  = opts.lt != null ? opts.lt - 1 : opts.lte != null ? opts.lte : null
+      var limit = opts.limit ? opts.limit : Infinity
       var cursor = reverse ? max || log.length - 1 : min
       var values = opts.values !== false, seqs = opts.seqs !== false
       var live = opts.live === true
@@ -87,6 +88,7 @@ module.exports = function (filename) {
           if(cleanup) {cleanup(); _cb(abort) }
           return cb(abort)
         }
+        else if (limit-- === 0) cb(true)
         else if (cursor < min) cb(true)
         else if(!live && cursor > (max === null ? log.length-1 : max)) cb(true)
         else if(cursor >= log.length) {
```

**Comment by dominictarr** [comment]
this module reuses the same tests as the other flumelogs, so if there is a problem with the tests it's a big problem. I updated the tests, and realized there was a bug, and that the best way to fix it was to use `pull-cursor` which is also used to implement the stream on flumelog-offset (which is the recommended implementation ;) I think that may have fixed this? if not we should add a test for `limit` to https://github.com/flumedb/test-flumelog

**Comment by marcbachmann** [comment]
Oh, you already rewrote it. I also just did the same and wanted to push 😆.

The test failure is only in the `live` option. You probably already saw that.
I'm not using that yet, but I don't think that the live stream should end unless you explicitly end it.
So the test might be wrong where it expects to end once.

**Comment by marcbachmann** [comment]
Closing this as it landed in v0.1.3 https://github.com/flumedb/flumelog-memory/commit/41c1b468fc8d44fb93661e8939ef721b975f04cd

**Comment by dominictarr** [comment]
one situation where the the live stream would end even if not by you, is if you closed the database.

**Comment by marcbachmann** [comment]
FYI the issue I had with the `live` stream was that I didn't have anything queued up in the node event loop 🤦‍♂️ 
I expected that there's a file descriptor or something that keeps the process from exiting, but that isn't the case.

**Comment by dominictarr** [comment]
that is the case with network connections but not with files! but setTimeout/setInterval do it too.
